version: "3"
services:
  server:
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    command: make watch-server
    volumes:
      - .:/go/src/${PROJECT_PATH}/
    env_file: .env
    environment:
      - APP_ENV=dev
      - DEBUG=true
    ports:
      - ${SERVER_HOST_PORT}:9000
    links:
      - db:${IMAGE_NAME}-pgdb
      - sftp
    depends_on:
      - db
      - sftp

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=America/Los_Angeles
      - PGTZ=America/Los_Angeles
    volumes:
      - ./database/init/:/docker-entrypoint-initdb.d/
    ports:
      - ${POSTGRES_HOST_PORT}:5432

  sftp:
    image: atmoz/sftp
    volumes:
      - ./testing/fixtures/sftp-data/:/home/sftp-data/
    ports:
      - ${SFTP_HOST_PORT}:22
    command: ${SFTP_USER}:${SFTP_PASS}:${SFTP_UID}
